security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
      
#logging:
#  level:
#    org.springframework.data.rest: debug

# spring data REST 엔드포인트의 기본 경로를 /api로 설정
# http://localhost:8080/api/tacos
spring:
  data:
    rest:
      base-path: /api

---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
    
logging:
  level:
    tacos: WARN
    
